#!/bin/bash
#
# This is a small shellscript to mount an encrypted Luks Container.

# Name of the mount directory and the device mapper.
NAME="Lamotta"
# Path to the mount directory. Default is /media/$user/$NAME
MOUNTPOINT="/media/`logname`/$NAME"
# UUID of the partition that should be mounted
UUID="f1022754-8776-4be8-9273-935c9c3cb0a8"

# MOUNT DEVICE
if [ $# -eq 0 ]
then
	if mkdir -p $MOUNTPOINT
	then
		if cryptsetup luksOpen UUID=$UUID $NAME
		then
			if mount /dev/mapper/$NAME $MOUNTPOINT
			then
				echo "$NAME mounted in $MOUNTPOINT"
			else
				cryptsetup luksClose $NAME
				rmdir $MOUNTPOINT
				echo "Unable to mount $NAME in $MOUNTPOINT"
			fi
		else
			rmdir $MOUNTPOINT
			echo "Unable to encrypt $UUID"
		fi
	fi
else
	# UNMOUNT DEVICE
	if [ $# -eq 1 ]
	then
		if [ $1 == "-u" ]
		then
			umount $MOUNTPOINT
			cryptsetup luksClose $NAME
			rmdir $MOUNTPOINT
		else
			echo "USAGE:"
			echo "  $0     - to mount"
			echo "  $0 -u  - to unmount"
		fi
	else
		echo "USAGE:"
		echo "  $0     - to mount"
		echo "  $0 -u  - to unmount"
	fi
fi
