#!/bin/bash
#
# This is a small shellscript to mount an encrypted Luks Container.

# Name of the mount directory and the device mapper.
NAME="Windows"
# Path to the mount directory. Default is /media/$user/$NAME
MOUNTPOINT="/media/`logname`/$NAME"
# UUID of the partition that should be mounted
UUID="18CA606DCA6048D8"

# MOUNT DEVICE
if [ $# -eq 0 ]
then
	if mkdir -p $MOUNTPOINT
	then
		if mount --uuid=$UUID $MOUNTPOINT
		then
			echo "$NAME mounted in $MOUNTPOINT"
		else
			rmdir $MOUNTPOINT
			echo "Unable to mount $NAME in $MOUNTPOINT"
		fi
	fi
else
	# UNMOUNT DEVICE
	if [ $# -eq 1 ]
	then
		if [ $1 == "-u" ]
		then
			umount $MOUNTPOINT
			rmdir $MOUNTPOINT
		else
			echo "USAGE:"
			echo "  $0     - to mount"
			echo "  $0 -u  - to unmount"
		fi
	else
		echo "USAGE:"
		echo "  $0     - to mount"
		echo "  $0 -u  - to unmount"
	fi
fi
